version: '3'
services: 
    master:
        image: redis
        container_name: redis-master
        volumes: 
        - ./data/redis-master/data:/data
        ports: 
        - 6379:6379
    slave1:
        image: redis
        container_name: redis-slave1
        volumes: 
        - ./data/redis-slave1/data:/data
        ports: 
        - 6380:6379
        command: redis-server --slaveof redis-master 6379 --repl-diskless-load on-empty-db
        depends_on: 
        - master
    slave2:
        image: redis
        container_name: redis-slave2
        volumes: 
        - ./data/redis-slave2/data:/data
        ports: 
        - 6381:6379
        command: redis-server --slaveof redis-master 6379 --repl-diskless-load on-empty-db
        depends_on: 
        - master
        - slave1
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
        - REDIS_HOSTS=master:redis-master,slave-1:redis-slave1,slave-2:redis-slave2
        ports:
        - "8081:8081"